import Button from "@/components/Button/Button";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>EduStage</h1>
      <Button text={"Learn more"} blue={false} />
      <Button text={"Learn more"} blue={true} />
    </>
  );
}
