import { CourseCard } from "@/components";
import { CourseElement } from "@/utils/data/CourseData";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {CourseElement.map((item, index) => {
        return <CourseCard {...item} key={index} />;
      })}

      <h1>EduStage</h1>
    </>
  );
}
